import type { LayoutSetting } from '~@/stores/app'

export default {
  title: '迅联API',
  theme: 'light',
  logo: '/public/favicon.ico',
  collapsed: false,
  drawerVisible: false,
  colorPrimary: '#1677FF',
  layout: 'top',
  // layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixedSider: true,
  splitMenus: false,
  header: true,
  menu: true,
  menuHeader: true,
  footer: false,
  colorWeak: false,
  multiTab: true,
  multiTabFixed: false,
  headerHeight: 48,
  copyright: 'xiaoxi2023',
} as LayoutSetting
