server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=api_source, xiaoxi_api_gateway
        - AddResponseHeader=api_source, xiaoxi_api_gateway
      routes:
        - id: api_route
          uri: http://127.0.0.1:8123
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: api_consumer
    qos-enable: true
    qos-accept-foreign-ip: false
    qos-port: 22202
  protocol:
    name: dubbo
    port: -1
  registry:
    id: gateway
    #    address: nacos://8.140.60.185:8848
    address: nacos://127.0.0.1:8848
  config-center:
    timeout: 40000



